# @package _global_

defaults:
  - ../architecture/gpt2

data:
  dataloader:
    max_length: 256

model:
  config_kwargs:
    n_ctx: ${data.dataloader.max_length}
    n_positions: ${data.dataloader.max_length}
    n_layer: 2
    n_head: 2
    n_embd: 256