# @package _global_

defaults:
  - ../architecture/mamba

data:
  dataloader:
    max_length: 1024

model:
  config_kwargs:
    d_model: 4096
    n_layer: 184
    num_hidden_layers: 184
    state_size: 64
